In [2]:
#very cool notebook to mess around and try things until we get a working baseline

In [54]:
#imports, add more as needed
import os

import numpy as np

import sklearn as skl

from sklearn import model_selection

import tensorflow as tf

from matplotlib import pyplot

from geopy.geocoders import Nominatim

from tensorflow.keras import Sequential

from tensorflow.keras.layers import Dense

from tensorflow.keras.losses import SparseCategoricalCrossentropy


In [4]:
#initiate nominatim geolocator

geolocator = Nominatim(user_agent="geoapiExercises")


In [46]:
#data loading

X_data = np.loadtxt(os.path.join('data', 'default_plus_chromatic_features_1059_tracks.txt'), delimiter=',')
Y_data = np.loadtxt(os.path.join('data', 'Y_encoding.txt'), delimiter=',')
X = data[:, :116]
y = Y_data

[[ 7.161286  7.835325  2.911583 ... -0.364194 -0.364194 -0.364194]
 [ 0.225763 -0.094169 -0.603646 ...  0.936616  0.936616  0.936616]
 [-0.692525 -0.517801 -0.788035 ...  0.603755  0.603755  0.603755]
 ...
 [-0.77236  -0.670596 -0.84042  ... -0.515309 -0.515309 -0.515309]
 [-0.996965 -1.099395  3.515274 ...  0.074855  0.074855  0.074855]
 [-0.150911 -0.094333 -0.568885 ...  5.835585  5.835585  5.835585]]


In [27]:
#translating longitude and latitude to country labels
''''Y_labels = []

y_unique = np.unique(y, axis=0)
#print(y_unique)

for point in range(0, y_unique.shape[0]):
    latitude = y_unique[point,0]
    longitude = y_unique[point,1]

    location = geolocator.reverse((latitude, longitude))
    
    
    Y_labels.append(location.raw['address']['country_code'])

print(Y_labels) '''


['au', 'br', 'tz', 'id', 'ke', 'et', 'kh', 'ml', 'th', 'sn', 'cv', 'bz', 'jm', 'mm', 'tw', 'in', 'eg', 'pk', 'ma', 'ir', 'jp', 'dz', 'gr', 'tr', 'cn', 'uz', 'al', 'ge', 'it', 'kg', 'ro', 'gb', 'lt']


In [43]:
#create one-hot encoded y matrix
'''num_labels = 33

Y_matrix = np.zeros((y.shape[0], num_labels))

for point in range(0, y.shape[0]):
    loc = np.where(y_unique == y[point, 0])[0]
    Y_matrix[point, loc] = 1'''



[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [44]:
#writing one-hot encoded matrix to new data file for ease of use
'''np.savetxt('Y_encoding.txt', Y_matrix, delimiter=',')'''


In [59]:
#splitting data into train, cv, test

split = skl.model_selection.train_test_split(X, y)

train_x = split[0]
train_y = split[2]

cv_split = skl.model_selection.train_test_split(split[1], split[3])

cv_x = cv_split[0]

cv_y = cv_split[2]

test_x = cv_split[1]

text_y = cv_split[3]


In [60]:
#One v. all logitistic regression for accuracy testing

regression_model = Sequential([
    Dense(units=33, activation = 'softmax')
])

regression_model.compile(loss=SparseCategoricalCrossentropy())

regression_model.fit(train_x, train_y, epochs=100)

Epoch 1/100


InvalidArgumentError: Graph execution error:

Detected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):
    File "C:\Users\Cassandra\.conda\envs\ml\lib\runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\Cassandra\.conda\envs\ml\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
      app.start()
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\ipykernel\kernelapp.py", line 711, in start
      self.io_loop.start()
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "C:\Users\Cassandra\.conda\envs\ml\lib\asyncio\base_events.py", line 603, in run_forever
      self._run_once()
    File "C:\Users\Cassandra\.conda\envs\ml\lib\asyncio\base_events.py", line 1906, in _run_once
      handle._run()
    File "C:\Users\Cassandra\.conda\envs\ml\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
      await result
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
      reply_content = await reply_content
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\ipykernel\ipkernel.py", line 411, in do_execute
      res = shell.run_cell(
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\ipykernel\zmqshell.py", line 531, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\IPython\core\interactiveshell.py", line 2940, in run_cell
      result = self._run_cell(
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\IPython\core\interactiveshell.py", line 2995, in _run_cell
      return runner(coro)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\IPython\core\interactiveshell.py", line 3194, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\IPython\core\interactiveshell.py", line 3373, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\Cassandra\AppData\Local\Temp\ipykernel_9476\3772407327.py", line 9, in <module>
      regression_model.fit(train_x, train_y, epochs=100)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\engine\training.py", line 1564, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\engine\training.py", line 1160, in train_function
      return step_function(self, iterator)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\engine\training.py", line 1146, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\engine\training.py", line 1135, in run_step
      outputs = model.train_step(data)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\engine\training.py", line 994, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\engine\training.py", line 1052, in compute_loss
      return self.compiled_loss(
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\losses.py", line 152, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\losses.py", line 272, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\losses.py", line 2084, in sparse_categorical_crossentropy
      return backend.sparse_categorical_crossentropy(
    File "C:\Users\Cassandra\.conda\envs\ml\lib\site-packages\keras\backend.py", line 5630, in sparse_categorical_crossentropy
      res = tf.nn.sparse_softmax_cross_entropy_with_logits(
Node: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'
logits and labels must have the same first dimension, got logits shape [32,33] and labels shape [1056]
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_904]